from printing_functions import print_models, show_completed_models

print_models.printing_functions(unprinted_designs, completed_models)
show_completed_models.printing_functions(completed_models)

help(print_models)
